#!/usr/bin/env python
# -*- coding: utf-8 -*-

#Highly divisible triangular number
#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#            1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#    10: 1,2,5,10
#    15: 1,3,5,15
#    21: 1,3,7,21
#    28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.
#What is the value of the first triangle number to have over five hundred divisors?


# La secuencia de los números de triángulos se genera al sumar los números naturales. Entonces, el número del séptimo triángulo sería 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. Los primeros diez términos serían:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Permítanos enumerar los factores de los primeros siete números de triángulos:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# Podemos ver que 28 es el primer número de triángulo que tiene más de cinco divisores.
# ¿Cuál es el valor del primer número de triángulo para tener más de quinientos divisores?


result = 0
quantity_div = 0
max = 501
contador = 1
while(quantity_div < max):
    result = result + contador
    contador += 1
    quantity_div = 0
    for element in range(1,result+1):
        if result % element == 0:
            quantity_div += 1


print ("El resultado es : {}".format(result))

#El resultado es : 76576500
    