#!/usr/bin/env python
# -*- coding: utf-8 -*-

#Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Cada nuevo término en la secuencia de Fibonacci se genera al agregar los dos términos anteriores. Al comenzar con 1 y 2, los primeros 10 términos serán:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# Al considerar los términos en la secuencia de Fibonacci cuyos valores no exceden los cuatro millones, encuentre la suma de los términos de valor par.

last_num = 0
fibonacci = 1
last_fibonacci = 0
sum = 0
while(fibonacci < 4000000):
    last_fibonacci = fibonacci
    fibonacci += last_num
    last_num = last_fibonacci
    sum = sum + fibonacci if fibonacci % 2 == 0 else sum

print ("El resultado es : {}".format(sum))

# El resultado es :  4613732