# Distinct powers
"""
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
"""
import time
start_time = time.time()
limit_down = 2
limit_up = 100

result = []
for a in range(limit_down, limit_up+1):
    for b in range(limit_down, limit_up+1):
        result.append(a ** b)

result = set(result)
print(len(result))
print("--- %s seconds ---" % (time.time() - start_time))
# 9183
# --- 0.006178855895996094 seconds ---
